#!/bin/bash

#this should run on Snap CI only
if [ ! "$SNAP_CI" = 'true' ]; then
  echo Cannot run outside build server
  exit 11
fi
echo $(date) Npm cleaning cache...
npm cache clean
echo $(date) Updating npm...
npm i -g npm@v3.x-latest
npm i -g grunt-cli bower
echo $(date) Npm pruning...
npm prune
echo $(date) Npm installing
for i in {1..3}; do npm install && break; done
echo $(date) Npm pruning again for the cache...
npm prune
echo $(date) Finished npm install
