#!/bin/bash


echo $(date) Getting current environment name from AWS...
currEnv=`./node_modules/.bin/coffee --eval "console.log JSON.parse('$(aws elasticbeanstalk describe-environments --application-name atelies)').Environments[0].EnvironmentName"`
echo $(date) Current environment name is $currEnv
echo $(date) Getting current public script version from AWS...
currVersion=`./node_modules/.bin/coffee --eval "console.log (o for o in JSON.parse('$(aws elasticbeanstalk describe-configuration-settings --application-name atelies --environment-name prod-blue)').ConfigurationSettings[0].OptionSettings when o.OptionName is 'CLIENT_LIB_VERSION')[0].Value"`
echo $(date) Current public script version is $currVersion
newVersion=`echo "0.01 + $currVersion" | bc`
echo $(date) Will use version $newVersion for this public scripts environment

echo $(date) Starting to update AWS
revName=zip-`git rev-parse HEAD`-`date +%Y%m%d%H%M%S`
revNameShort=git-`git rev-parse --short HEAD`-`date +%H%M%S`
zipName=$revName.zip
echo $(date) Preparing rev with name $revName and zip name $zipName
echo $(date) Checking out files...
#git checkout .
echo $(date) Zipping...
zip -r $zipName . -x "node_modules/*" "seed/*" "test/*" "compilePublic/*" "public/*" "log/*" ".uploadPublicFiles/*" "misc/*" ".git/*" "TAGS" ".s3cfg" "Session.vim" ".vimrc.local" "Procfile" ".travis.yml" ".ebextensions/030_compileServer.config"
echo $(date) Uploading to S3...
aws s3 cp $zipName s3://elasticbeanstalk-us-east-1-467348781193/$zipName
echo $(date) Creating app version...
aws elasticbeanstalk create-application-version --application-name atelies --version-label $revName --source-bundle S3Bucket=elasticbeanstalk-us-east-1-467348781193,S3Key=$zipName
echo $(date) Creating environment...
aws elasticbeanstalk create-environment --application-name atelies --environment-name $revNameShort --template works20140706 --tier "Name=WebServer,Type=Standard,Version=1.0" --version-label $revName --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=CLIENT_LIB_VERSION,Value=$newVersion
echo $(date) Done publishing to AWS server
